apiVersion: v2
appVersion: 7.39.4
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.jfrog.io/
  version: 10.3.18
- condition: rabbitmq.enabled
  name: rabbitmq
  repository: https://charts.jfrog.io/
  version: 8.31.6
- condition: redis.enabled
  name: redis
  repository: https://charts.jfrog.io/
  version: 12.10.1
- condition: artifactory.enabled
  name: artifactory
  repository: https://charts.jfrog.io/
  version: 107.39.4
- condition: xray.enabled
  name: xray
  repository: https://charts.jfrog.io/
  version: 103.49.0
- condition: distribution.enabled
  name: distribution
  repository: https://charts.jfrog.io/
  version: 102.12.3
- condition: insight.enabled
  name: insight
  repository: https://charts.jfrog.io/
  version: 101.10.2
- condition: pipelines.enabled
  name: pipelines
  repository: https://charts.jfrog.io/
  version: 101.23.6
description: The Helm chart for JFrog Platform (Universal, hybrid, end-to-end DevOps
  automation)
home: https://jfrog.com/platform/
icon: https://raw.githubusercontent.com/jfrog/charts/master/stable/jfrog-platform/logo/jfrog-platform-logo.png
keywords:
- platform
- artifactory
- jfrog
- devops
kubeVersion: '>= 1.14.0-0'
maintainers:
- email: installers@jfrog.com
  name: Chart Maintainers at JFrog
name: jfrog-platform
sources:
- https://github.com/jfrog/charts
type: application
version: 10.6.3
