{{- if and (not .Values.vault.existingSecret) (.Values.vault.enabled) -}}
apiVersion: v1
kind: Secret
metadata:
  name: vault-storage-config
  labels:
    {{- include "pipelines.labels" . | nindent 4 }}
    component: {{ include "pipelines.vault.name" . }}
type: Opaque
data:
{{- if .Values.global.postgresql.url }}
  postgresql-url: {{ .Values.global.postgresql.url | b64enc }}
{{- else if .Values.postgresql.enabled }}
  postgresql-url: {{ (printf "postgres://%s:%s@%s-postgresql:%v/%s?sslmode=disable" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword .Release.Name .Values.postgresql.service.port .Values.postgresql.postgresqlDatabase) | b64enc }}
{{- else if and (not .Values.postgresql.enabled) (.Values.global.postgresql.ssl) }}
  postgresql-url: {{ tpl (printf "postgres://%s:%s@%v:%v/%s?sslmode=require" .Values.global.postgresql.user .Values.global.postgresql.password .Values.global.postgresql.host .Values.global.postgresql.port .Values.global.postgresql.database) . | b64enc }}
{{- else }}
  postgresql-url: {{ tpl (printf "postgres://%s:%s@%v:%v/%s?sslmode=disable" .Values.global.postgresql.user .Values.global.postgresql.password .Values.global.postgresql.host .Values.global.postgresql.port .Values.global.postgresql.database) . | b64enc }}
{{- end }}
stringData:
  config.hcl: |
    storage "postgresql" {
    {{- if .Values.postgresql.enabled }}
      connection_url = "{{ (printf "postgres://%s:%s@%s-postgresql:%v/%s?sslmode=disable" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword .Release.Name .Values.postgresql.service.port .Values.postgresql.postgresqlDatabase) }}"
    {{- else if and (not .Values.postgresql.enabled) (.Values.global.postgresql.ssl) }}
      connection_url = "{{ tpl (printf "postgres://%s:%s@%v:%v/%s?sslmode=require" .Values.global.postgresql.user .Values.global.postgresql.password .Values.global.postgresql.host .Values.global.postgresql.port .Values.global.postgresql.database) . }}"
    {{- else }}
      connection_url = "{{ tpl (printf "postgres://%s:%s@%v:%v/%s?sslmode=disable" .Values.global.postgresql.user .Values.global.postgresql.password .Values.global.postgresql.host .Values.global.postgresql.port .Values.global.postgresql.database) . }}"
    {{- end }}
      ha_enabled = "{{ .Values.vault.server.ha.enabled }}"
    }
{{- end -}}
